name: Tests

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta
  workflow_dispatch:

jobs:
  test-library:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22, 23]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
